#!/usr/bin/env python3

import sys,json
import requests
from requests.auth import HTTPBasicAuth

def on_publish_success(message):
    with open('/var/ossec/logs/integrations.log', 'a') as f:
        f.write(f"Alert Level : {message}\n")

alert_file = open(sys.argv[1])
hook_url = sys.argv[3]

alert_json =  json.loads(alert_file.read())
alert_file.close()

alert_level = alert_json['rule']['level']


headers = {'Content-type':'application/json'}
issue_data = {
    'level' : alert_level
}

try:
    response = requests.post(hook_url, headers=headers, data=json.dumps(issue_data))
    on_publish_success(alert_level)

except KeyboardInterrupt:
    client.disconnect()
    print("Disconnected from the broker")
sys.exit(0)
